services:
  configsvr01:
    image: mongo:latest
    container_name: configsvr01
    command: mongod --configsvr --replSet cfgrs --port 27017 --bind_ip_all
    volumes:
      - ./data/config01:/data/db

  configsvr02:
    image: mongo:latest
    container_name: configsvr02
    command: mongod --configsvr --replSet cfgrs --port 27017 --bind_ip_all
    volumes:
      - ./data/config02:/data/db

  configsvr03:
    image: mongo:latest
    container_name: configsvr03
    command: mongod --configsvr --replSet cfgrs --port 27017 --bind_ip_all
    volumes:
      - ./data/config03:/data/db

  shard1a:
    image: mongo:latest
    container_name: shard1a
    command: mongod --shardsvr --replSet shard1rs --port 27017 --bind_ip_all
    volumes:
      - ./data/shard1a:/data/db

  shard1b:
    image: mongo:latest
    container_name: shard1b
    command: mongod --shardsvr --replSet shard1rs --port 27017 --bind_ip_all
    volumes:
      - ./data/shard1b:/data/db

  shard2a:
    image: mongo:latest
    container_name: shard2a
    command: mongod --shardsvr --replSet shard2rs --port 27017 --bind_ip_all
    volumes:
      - ./data/shard2a:/data/db

  shard2b:
    image: mongo:latest
    container_name: shard2b
    command: mongod --shardsvr --replSet shard2rs --port 27017 --bind_ip_all
    volumes:
      - ./data/shard2b:/data/db

  shard3a:
    image: mongo:latest
    container_name: shard3a
    command: mongod --shardsvr --replSet shard3rs --port 27017 --bind_ip_all
    volumes:
      - ./data/shard3a:/data/db

  shard3b:
    image: mongo:latest
    container_name: shard3b
    command: mongod --shardsvr --replSet shard3rs --port 27017 --bind_ip_all
    volumes:
      - ./data/shard3b:/data/db

  mongos:
    image: mongo:latest
    container_name: mongos
    command: mongos --configdb cfgrs/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all --port 27017
    ports:
      - "27117:27017"
    depends_on:
      - configsvr01
      - shard1a
      - shard2a
      - shard3a